/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R404RouteImport } from './routes/404'
import { Route as DocumentationRouteImport } from './routes/documentation'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ReferralsRouteImport } from './routes/referrals'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as SupportRouteImport } from './routes/support'
import { Route as PayIdRouteImport } from './routes/pay.$id'
import { Route as RCodeRouteImport } from './routes/r.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationRoute = DocumentationRouteImport.update({
  id: '/documentation',
  path: '/documentation',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const PayIdRoute = PayIdRouteImport.update({
  id: '/pay/$id',
  path: '/pay/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/documentation': typeof DocumentationRoute
  '/how-it-works': typeof HowItWorksRoute
  '/referrals': typeof ReferralsRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/support': typeof SupportRoute
  '/pay/$id': typeof PayIdRoute
  '/r/$code': typeof RCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/documentation': typeof DocumentationRoute
  '/how-it-works': typeof HowItWorksRoute
  '/referrals': typeof ReferralsRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/support': typeof SupportRoute
  '/pay/$id': typeof PayIdRoute
  '/r/$code': typeof RCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/documentation': typeof DocumentationRoute
  '/how-it-works': typeof HowItWorksRoute
  '/referrals': typeof ReferralsRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/support': typeof SupportRoute
  '/pay/$id': typeof PayIdRoute
  '/r/$code': typeof RCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/documentation'
    | '/how-it-works'
    | '/referrals'
    | '/refund-policy'
    | '/support'
    | '/pay/$id'
    | '/r/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/documentation'
    | '/how-it-works'
    | '/referrals'
    | '/refund-policy'
    | '/support'
    | '/pay/$id'
    | '/r/$code'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/documentation'
    | '/how-it-works'
    | '/referrals'
    | '/refund-policy'
    | '/support'
    | '/pay/$id'
    | '/r/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  DocumentationRoute: typeof DocumentationRoute
  HowItWorksRoute: typeof HowItWorksRoute
  ReferralsRoute: typeof ReferralsRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  SupportRoute: typeof SupportRoute
  PayIdRoute: typeof PayIdRoute
  RCodeRoute: typeof RCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation': {
      id: '/documentation'
      path: '/documentation'
      fullPath: '/documentation'
      preLoaderRoute: typeof DocumentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$id': {
      id: '/pay/$id'
      path: '/pay/$id'
      fullPath: '/pay/$id'
      preLoaderRoute: typeof PayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  DocumentationRoute: DocumentationRoute,
  HowItWorksRoute: HowItWorksRoute,
  ReferralsRoute: ReferralsRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  SupportRoute: SupportRoute,
  PayIdRoute: PayIdRoute,
  RCodeRoute: RCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
